name: exp_tracker
description: A new Flutter project for Group 2 Expense Tracking.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons for the UI
  cupertino_icons: ^1.0.2

  # Hive Database Dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter rules to fix your analysis_options.yaml error
  flutter_lints: ^3.0.0

  # Code generation for Hive TypeAdapters
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # If you plan to add images or custom fonts later, 
  # they will be defined here:
  # assets:
  #   - assets/images/logo.png